language: node_js
node_js:
- "6"

cache:
  directories:
    - node_modules

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli

script:
  - ng build --prod
  - echo "Deploying!"

after_success:
  - firebase deploy --token 1/Et4EiGe6Hon3_rkt_qD8T6nymzkJe4H4sltMpPSG8hM