language: node_js
node_js:
- "6"

cache:
  directories:
    - node_modules

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli

script:
  - ng build --prod
  - echo "Deploying!"
  
after_sucess:
  - firebase deploy --token $FIREBASE_TOKEN